CREATE TABLE productos(
id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nombre VARCHAR2(100) NOT NULL,
descripcion VARCHAR2(100),
precio NUMBER(8,2) NOT NULL CHECK (precio >= 0),
stock NUMBER DEFAULT 0 NOT NULL,
fecha_registro DATE DEFAULT SYSDATE,
descuento NUMBER CHECK (descuento BETWEEN 0 AND 100),
estado VARCHAR2(10) DEFAULT 'activo' CHECK (estado IN ('activo', 'inactivo'))
);

ALTER TABLE productos ADD tipo VARCHAR2(50);

ALTER TABLE productos MODIFY descripcion VARCHAR2(500);

DROP TABLE productos;